ar3:
    hardware_interface:
        joint_offsets: # degrees
            joint_1: 0.0 # default -170.0
            joint_2: 0.0 # default -39.6
            joint_3: 90.0 # default 0.0
            joint_4: 0.0 # default -164.5
            joint_5: 0.0 # default -104.15
            joint_6: 0.0 # default -148.1
